# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{os-opendata-utils}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Neil Smith"]
  s.date = %q{2010-04-14}
  s.description = %q{Utilities for dealing with the Ordance Survey Open Data postcode data files, including latitude/longitude conversion.}
  s.email = %q{neil.jx.smith@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "VERSION",
     "init.rb",
     "lib/os_opendata_utils/grid_reference.rb",
     "lib/os_opendata_utils/lat_lng.rb",
     "lib/os_opendata_utils/ref_ell.rb",
     "lib/os_opendata_utils/utilities.rb"
  ]
  s.homepage = %q{http://github.com/smugx/os-opendata-utils}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ordnance Survey Open Data Utilities}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

